
### docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - chromadb
      - kafka
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  chromadb:
    image: "chromadb/chromadb"
    ports:
      - "8001:8001"
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"