apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-shard-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-shard-1
  template:
    metadata:
      labels:
        app: mysql-shard-1
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "app_db1"
          ports:
            - containerPort: 3306
