name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on main branch push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --disable-warnings

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Runs only if tests pass
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/app-system:latest .

      - name: Push to Docker Hub
        run: docker push your-dockerhub-username/app-system:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes Context
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f kubernetes/
